#pragma once

//#define ENABLE_REVERSING

#define ENABLE_SD_PATCHES
//#define ENABLE_LOW_SPEED_PATCH 

//#define ENABLE_NETWORK
//#define ENABLE_NETWORK_REPORT_SEND_FAILURE

//#define ENABLE_IO_FILE_OPEN_LOG